# .rubocop.yml
AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "config/puma.rb"
    - "config/environments/"
    - "spec/*"
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
require:
  - rubocop-rails
